# Generated by Django 5.0.2 on 2024-05-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('observacoes', models.CharField(max_length=255, null=True)),
                ('dataRecebimento', models.DateField()),
                ('dataEntrega', models.DateField(null=True)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peca', models.TextField(max_length=100)),
                ('cor', models.TextField(max_length=20, null=True)),
                ('qtd', models.IntegerField()),
                ('pedido', models.ManyToManyField(to='core.pedidos')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
